[package]
name = "vero-scanner-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
regex = "1"
rayon = "1"
audit-guard = { path = "../src/audit-guard" }
windows-sys = "=0.52.0"
winapi-util = "=0.1.9"

[[bin]]
name = "scanner"
path = "src/main.rs"
